### ISSUE TITLE
xcode build error: "Scheme not currently configured for clean action"

### ISSUE THREAD

**Issue by justinmakaila** [bitrise-steplib/steps-carthage#34] opened 2017-01-17 21:37 UTC
While attempting to run `carthage update --platform iOS --no-use-binaries` on a remote Bitrise machine with the "Xcode 8.2.x, on macOS 10.12 (Sierra)" stack, I get the following error:
```shell
Running Carthage command
Appending GITHUB_ACCESS_TOKEN to process environments
$ carthage "update" "--platform" "iOS" "--no-use-binaries"

*** Cloning AKPickerView-Swift
*** Cloning mixpanel-iphone
*** Cloning SwiftyJSON
*** Cloning GraphQLMapping
*** Cloning ReactiveCocoa
*** Cloning Moya
*** Cloning Nimble
*** Cloning Quick
*** Cloning Permission
*** Cloning KeychainAccess
*** Cloning FLAnimatedImage
*** Cloning libPhoneNumber-iOS
*** Cloning Swift-GraphQL
*** Cloning R.swift.Library
*** Cloning CoreDataStack
*** Cloning CameraKit
*** Cloning Eureka
*** Cloning AlamofireImage
*** Cloning CollapsableTable
*** Cloning SVProgressHUD
*** Cloning TTTAttributedLabel
*** Cloning RemoteMapping
*** Cloning ReactiveSwift
*** Cloning Alamofire
*** Cloning RxSwift
*** Cloning Result
*** Checking out AKPickerView-Swift at "94ddc2da5380c9fb1c4ed2527b3e8de334f2f7e7"
*** Checking out Alamofire at "4.3.0"
*** Checking out AlamofireImage at "3.2.0"
*** Checking out CameraKit at "1.9.0"
*** Checking out CollapsableTable at "1.1.0"
*** Checking out CoreDataStack at "1.0"
*** Checking out Eureka at "2.0.0-beta.1"
*** Checking out FLAnimatedImage at "1.0.12"
*** Checking out KeychainAccess at "v3.0.1"
*** Checking out libPhoneNumber-iOS at "0.9.2"
*** Checking out mixpanel-iphone at "97d1a9341cb0f12ada9a521743ac84247f48145a"
*** Checking out Nimble at "v5.1.1"
*** Checking out Permission at "v2.0.1"
*** Checking out Quick at "v0.10.0"
*** Checking out R.swift.Library at "v3.0.2"
*** Checking out RemoteMapping at "1.2.0"
*** Checking out Result at "3.1.0"
*** Checking out ReactiveSwift at "1.0.0"
*** Checking out ReactiveCocoa at "99db7971d14b426bc1a01375439ea9253e517cbf"
*** Checking out RxSwift at "3.1.0"
*** Checking out Moya at "805e98152aff1f0e0bb8bbfc2ec7e49bdd3600a0"
*** Checking out SVProgressHUD at "2.1.2"
*** Checking out Swift-GraphQL at "1.1.0"
*** Checking out GraphQLMapping at "1.0.0"
*** Checking out SwiftyJSON at "adf34cfb4c9f2ff4e3c420c6d9fb1e2eaf3b3791"
*** Checking out TTTAttributedLabel at "2.0.0"
*** xcodebuild output can be found in /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/carthage-xcodebuild.Mmg1Xj.log
*** Building scheme "AKPickerView" in AKPickerViewSample.xcodeproj
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task (/usr/bin/xcrun xcodebuild -project /Users/vagrant/git/Carthage/Checkouts/libPhoneNumber-iOS/libPhoneNumber.xcodeproj -scheme libPhoneNumber -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme libPhoneNumber is not currently configured for the clean action.
```
It's worth mentioning that this command works locally with `update` and `bootstrap`.

*EDIT*: libPhoneNumber shouldn't even be the one built after `Alamofire`. I'm really not sure what I'm doing wrong.

**Comment by viktorbenei** [comment] 2017-01-17 21:41
Did you run the __same__ command locally? `carthage "update" "--platform" "iOS" "--no-use-binaries"` (from the log)?

Also, did you try to run this __after a clean git clone__ of your repository (into a new directory)?

**Comment by justinmakaila** [comment] 2017-01-17 22:08
@viktorbenei this is run in my workflow using the default clone repo step, so i imagine a new machine is spun up, and everything is cloned clean.

On my local machine, I got a new error:
```
A shell task (/usr/bin/xcrun xcodebuild -workspace /path/to/app/MyApp/Carthage/Checkouts/Moya/Demo/Demo.xcworkspace -scheme MoyaTests-tvOS -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme MoyaTests-tvOS is not currently configured for the clean action.
```

Running the command without the quotes is giving me another different (but familiar) error:
```
/// ... truncated
*** xcodebuild output can be found in /var/folders/g0/9mlf9nxs5s5_4p9_y5bg8cxw0000gn/T/carthage-xcodebuild.JWaIOb.log
*** Building scheme "AKPickerView" in AKPickerViewSample.xcodeproj
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task (/usr/bin/xcrun xcodebuild -workspace /path/to/app/MyApp/Carthage/Checkouts/Moya/Demo/Demo.xcworkspace -scheme MoyaTests-Mac -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme MoyaTests-Mac is not currently configured for the clean action.
```

After removing `Carthage/` and running `carthage update --platform iOS --no-use-binaries`, it gets past `Alamofire iOS` and builds just fine.

**Comment by justinmakaila** [comment] 2017-01-17 22:10
I'm not sure if this is a stack error, a carthage error, or a local caching error (invalid files in my repo?). I have never experienced those errors on my local machine until today when following up to your post.

**Comment by viktorbenei** [comment] 2017-01-17 22:16
It's most likely either carthage or carthage config issue in your project, if it doesn't work locally on your Mac.

Once you sort it out, and you can `carthage bootstrap ...` on your Mac _after a clean git clone_, it should work on [bitrise.io](https://www.bitrise.io) too.

**Comment by justinmakaila** [comment] 2017-01-17 22:33
So running it on a clean clone worked perfectly fine, but starting a new Bitrise build still gives me the same error.

Local Output:
```shell
user> git clone https://github.com/myorganization/myrepo.git
Cloning into 'myrepo'...
remote: Counting objects: 19571, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 19571 (delta 2), reused 0 (delta 0), pack-reused 19549
Receiving objects: 100% (19571/19571), 235.95 MiB | 3.24 MiB/s, done.
Resolving deltas: 100% (13328/13328), done.
```
```shell
user> carthage bootstrap --no-use-binaries --platform iOS
*** Checking out AKPickerView-Swift at "94ddc2da5380c9fb1c4ed2527b3e8de334f2f7e7"
*** Checking out Alamofire at "4.2.0"
*** Checking out AlamofireImage at "3.2.0"
*** Checking out CameraKit at "1.9.0"
*** Checking out CollapsableTable at "1.1.0"
*** Checking out CoreDataStack at "1.0"
*** Checking out Eureka at "2.0.0-beta.1"
*** Checking out FLAnimatedImage at "1.0.12"
*** Checking out KeychainAccess at "v3.0.1"
*** Checking out libPhoneNumber-iOS at "0.9.1"
*** Checking out mixpanel-iphone at "d6670690a85ee65be80747eee11990ecc1683914"
*** Checking out Nimble at "v5.1.1"
*** Checking out Permission at "v2.0.1"
*** Checking out Quick at "v0.10.0"
*** Checking out R.swift.Library at "v3.0.2"
*** Checking out RemoteMapping at "1.2.0"
*** Checking out Result at "3.1.0"
*** Checking out ReactiveSwift at "1.0.0-alpha.4"
*** Checking out ReactiveCocoa at "82e2d87f075a8b41b682a65d646622bb8a95108c"
*** Checking out RxSwift at "3.0.1"
*** Checking out Moya at "95ff8e83f845f8314bdea255c75786b935648774"
*** Checking out SVProgressHUD at "2.0.4"
*** Checking out Swift-GraphQL at "1.0.0"
*** Checking out GraphQLMapping at "1.0.0"
*** Checking out SwiftyJSON at "c2024dce53377fbc04015597c5f7e9bd29249854"
*** Checking out TTTAttributedLabel at "2.0.0"
*** xcodebuild output can be found in /var/folders/g0/9mlf9nxs5s5_4p9_y5bg8cxw0000gn/T/carthage-xcodebuild.RlxYuV.log
*** Building scheme "AKPickerView" in AKPickerViewSample.xcodeproj
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "AlamofireImage iOS" in AlamofireImage.xcworkspace
*** Building scheme "CameraKit" in CameraKit.xcodeproj
*** Building scheme "CollapsableTable" in CollapsableTable.xcodeproj
*** Building scheme "CoreDataStack-iOS" in CoreDataStack.xcodeproj
*** Building scheme "Eureka" in Eureka.xcworkspace
--- xcodebuild: WARNING: Unable to open project file '/path/to/repo/Carthage/Checkouts/Eureka/Eureka.playground' in workspace '/path/to/repo/Carthage/Checkouts/Eureka/Eureka.xcworkspace'.
/// Truncated!
```

Remote:
```shell
+------------------------------------------------------------------------------+
| (3) carthage@3.0.4                                                           |
+------------------------------------------------------------------------------+
| id: carthage                                                                 |
| version: 3.0.4                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-01-17T14:39:54-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[14:39:54]  * [OK] Step dependency (go) installed, available. 
INFO[14:39:54]  * [OK] Step dependency (carthage) installed, available. 

Configs:
- CarthageCommand: bootstrap
- CarthageOptions: --platform iOS --no-use-binaries
- GithubAccessToken: ***

Check if cache is available
has cached items: false

Running Carthage command
Appending GITHUB_ACCESS_TOKEN to process environments
$ carthage "bootstrap" "--platform" "iOS" "--no-use-binaries"

*** Cloning AKPickerView-Swift
*** Cloning Alamofire
*** Cloning CameraKit
*** Cloning CollapsableTable
*** Cloning CoreDataStack
*** Cloning Eureka
*** Cloning FLAnimatedImage
*** Cloning KeychainAccess
*** Cloning Nimble
*** Cloning Permission
*** Cloning Quick
*** Cloning R.swift.Library
*** Cloning RemoteMapping
*** Cloning Result
*** Cloning RxSwift
*** Cloning SVProgressHUD
*** Cloning Swift-GraphQL
*** Cloning SwiftyJSON
*** Cloning TTTAttributedLabel
*** Cloning libPhoneNumber-iOS
*** Cloning mixpanel-iphone
*** Cloning AlamofireImage
*** Cloning ReactiveSwift
*** Cloning GraphQLMapping
*** Cloning ReactiveCocoa
*** Cloning Moya
*** Checking out AKPickerView-Swift at "94ddc2da5380c9fb1c4ed2527b3e8de334f2f7e7"
*** Checking out Alamofire at "4.2.0"
*** Checking out AlamofireImage at "3.2.0"
*** Checking out CameraKit at "1.9.0"
*** Checking out CollapsableTable at "1.1.0"
*** Checking out CoreDataStack at "1.0"
*** Checking out Eureka at "2.0.0-beta.1"
*** Checking out FLAnimatedImage at "1.0.12"
*** Checking out KeychainAccess at "v3.0.1"
*** Checking out libPhoneNumber-iOS at "0.9.1"
*** Checking out mixpanel-iphone at "2d546fd14b1938c2568b8dbcc42ace935268ab94"
*** Checking out Nimble at "v5.1.1"
*** Checking out Permission at "v2.0.1"
*** Checking out Quick at "v0.10.0"
*** Checking out R.swift.Library at "v3.0.2"
*** Checking out RemoteMapping at "1.2.0"
*** Checking out Result at "3.1.0"
*** Checking out ReactiveSwift at "1.0.0-alpha.4"
*** Checking out ReactiveCocoa at "1cfd136db961376bafb9298c7a5d418689aed91c"
*** Checking out RxSwift at "3.0.1"
*** Checking out Moya at "67b02ae7f608711ca2d00c08fc6706951085c6af"
*** Checking out SVProgressHUD at "2.1.2"
*** Checking out Swift-GraphQL at "1.1.0"
*** Checking out GraphQLMapping at "1.0.0"
*** Checking out SwiftyJSON at "a7d83f0a55cda288e2c9c7cf14cd1d62f9b5752f"
*** Checking out TTTAttributedLabel at "2.0.0"
*** xcodebuild output can be found in /var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/carthage-xcodebuild.11nECa.log
*** Building scheme "AKPickerView" in AKPickerViewSample.xcodeproj
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task (/usr/bin/xcrun xcodebuild -project /Users/vagrant/git/Carthage/Checkouts/libPhoneNumber-iOS/libPhoneNumber.xcodeproj -scheme libPhoneNumber -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean -showBuildSettings) failed with exit code 66:
xcodebuild: error: Scheme libPhoneNumber is not currently configured for the clean action.


Carthage command failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | carthage@3.0.4 (exit code: 1)                                 | 168 sec  |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-carthage/issues      |
| Source: https://github.com/bitrise-steplib/steps-carthage                    |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment] 2017-01-17 23:07
- Do you use the same Xcode version locally and on bitrise.io?
- Do you have anything from the `Carthage` directory committed into your repository?
- What's the carthage version do you use? Is it the same as the one preinstalled on the Xcode 8.2 VM on bitrise.io ? https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-8.2.x.log#L43

Seems to be related: https://github.com/Carthage/Carthage/issues/1542

**Comment by justinmakaila** [comment] 2017-01-17 23:11
Xcode version 8.2.1
There's no `Carthage/` in my repository.
I'm on Carthage 0.18.1, which is the latest.

I'm not so sure it's related to that issue because it's building all of the schemes that fail successfully locally. That issue is related to the schemes not being shared, which is not the case.

**Comment by viktorbenei** [comment] 2017-01-17 23:15
Do you have the `Cartfile.resolved` in your repository?

**Comment by justinmakaila** [comment] 2017-01-17 23:16
Yes

**Comment by viktorbenei** [comment] 2017-01-17 23:25
Do you use the latest version of `libPhoneNumber`? If not, can you upgrade?

Can you try to `git clone` into `/tmp` and see if the issue happens there?

**Comment by viktorbenei** [comment] 2017-01-17 23:50
Also:

- did you try to run this locally with the Bitrise CLI (https://www.bitrise.io/cli)
- what do you get if you replace the Carthage step on bitrise.io with a Script where you run `carthage bootstrap ..` the way you run it locally?

**Comment by justinmakaila** [comment] 2017-01-18 17:49
@viktorbenei 

- `git clone` into my local `/tmp` dir and then run `carthage`?
- I'm going to give the local CLI a go now.
- Wouldn't I need to also include a script to install the carthage dependency and whatnot?

**Comment by viktorbenei** [comment] 2017-01-18 17:56
> git clone into my local /tmp dir and then run carthage?

```
cd /tmp
git clone git@my/repo quick-carthage-test
cd quick-carthage-test
```

> Wouldn't I need to also include a script to install the carthage dependency and whatnot?

`carthage` is preinstalled on the Xcode 8.2.x stack, so simply running the `carthage ..` command should be enough. Long term you should use this step instead, as it can manage e.g. the GitHub token, as well as it supports the Build Cache, etc., but for a minimal test a Script step with the `carthage ..` command would be enough

**Comment by justinmakaila** [comment] 2017-01-18 18:06
@viktorbenei 
Trying to run my `bitrise.yml` file locally doesn't actually do any of the cloning. I'd really like to create as close of an environment as possible to the VM. How can I achieve this?

```
| (0) activate-ssh-key@3.1.1                                                   |
+------------------------------------------------------------------------------+
| id: activate-ssh-key                                                         |
| version: 3.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-01-18T10:03:43-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
WARN[10:03:43] The step's (activate-ssh-key@3.1.1) Run-If expression evaluated to false - skipping 
INFO[10:03:43] The Run-If expression was: {{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}} 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| - | activate-ssh-key@3.1.1                                        | 0.27 sec |
+---+---------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (1) git-clone@3.4.1                                                          |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 3.4.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-01-18T10:03:43-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
WARN[10:03:43] The step's (git-clone@3.4.1) Run-If expression evaluated to false - skipping 
INFO[10:03:43] The Run-If expression was: .IsCI  
```

**Comment by justinmakaila** [comment] 2017-01-18 21:51
I just ran my `.yml` file in my local repository, and it runs fine, but still fails in Bitrise

**Comment by viktorbenei** [comment] 2017-01-19 06:41
Did you run it after

```
cd /tmp
git clone git@my/repo quick-carthage-test
cd quick-carthage-test
```

?

**Comment by justinmakaila** [comment] 2017-01-19 15:54
Yes. I cloned into `/tmp`, `cd`'d into my repo, and then ran
```
$> bitrise run --config /path/to/config MyWorkflow
```
Doing it again for a sanity check and it's working fine.

**Comment by viktorbenei** [comment] 2017-01-20 08:43
Can you share/send us a sample repo where we could reproduce this issue?

**Comment by justinmakaila** [comment] 2017-01-23 17:54
I'm currently setting up an empty repo with just the Cartfile. Going to see if I can recreate it with a new Bitrise app. Will report back.

**Comment by viktorbenei** [comment] 2017-01-23 19:10
That would be fantastic, thank you @justinmakaila !

**Comment by justinmakaila** [comment] 2017-01-24 16:11
@viktorbenei So I took the exact `Cartfile` from my problem repo and inserted it in a new repo. The new repo is just an empty single view application that has a view controller that imports every dependency (it doesn't use any of them). I ran this on Bitrise, and it executed perfectly fine, but when I attempt to run my problem app on Bitrise, it doesn't work.

The repo can be found here: github.com/justinmakaila/bitrise-issue-34

**Comment by viktorbenei** [comment] 2017-01-24 17:36
> I ran this on Bitrise, and it executed perfectly fine

Hmm.. The issue is, we'd need a project where we can reproduce the issue somehow.

So far the issue seems to be related to your repo somehow, maybe a gitignored file, or something what you did commit into your repo which you shouldn't.. But without a reproduction project.. I don't really have an idea how we could help, especially if the same Cartfile etc. works with another project (the sample you linked).

I'm a bit out of ideas..
One more thing, did you try to add the app again on bitrise.io? Maybe you have something in your app's current bitrise config which causes this issue.

**Comment by godrei** [comment] 2017-05-18 09:30
Closing as we did not receive a reply - @justinmakaila please let us know if we can help with anything and we'll reopen this issue!

**Closed as completed by godrei** 2017-05-18 09:30 UTC
Labels: question
