### ISSUE TITLE
Issue with carthage.resolved file

### ISSUE THREAD

**Issue by pakmee** [bitrise-steplib/steps-carthage#35] opened 2017-01-31 18:43 UTC
Hi there seems to be an issue with search path for the carthage.resolved file. It always seems to try an locate it in the root directory: https://github.com/bitrise-steplib/steps-carthage/blob/master/main.go#L212

**Comment by viktorbenei** [comment] 2017-01-31 18:46
That's not a bug, that's a feature! :D

More seriously, this was changed in an earlier version of this step: https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.0

But I think you're right that the workdir flag should affect the resolve file search path too.

@godrei ?

**Comment by viktorbenei** [comment] 2017-01-31 18:48
Btw a temporary solution is to use the __Change Working Directory__ step, instead of passing the workdir as a param for this step. That should work in every case, but I agree that this should be fixed too.

**Comment by pakmee** [comment] 2017-01-31 18:51
👍

**Comment by godrei** [comment] 2017-02-01 10:15
Hi @pakmee,

we removed `work_dir` property, since carthage has the same option: 

```
[--project-directory (string)]
	the directory containing the Carthage project
```

Could you please add `--project-directory YOUR_DIR` to the `carthage_options` input of the step?

This is covered in the migration guide for step version [3.0.0](https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.0).

**Comment by viktorbenei** [comment] 2017-02-01 10:16
That won't help @godrei as the resolve file search is in the step's code

**Comment by pakmee** [comment] 2017-02-01 12:35
@godrei yeah I am passing project-directory in but as @viktorbenei mentioned, the resolve file search is in the step's code.

**Comment by godrei** [comment] 2017-02-01 12:44
@pakmee we are waiting for the last ci workflow, the fix will be available soon.

From now the step will search for `--project-directory` flag, if it appears in the `carthage_options`, its value will be used as previous `work-dir`.

**Comment by pakmee** [comment] 2017-02-01 12:51
@godrei thanks !

**Comment by godrei** [comment] 2017-02-01 13:19
@pakmee new version ([3.0.5](https://github.com/bitrise-steplib/steps-carthage/releases/tag/3.0.5)) is available in the steplib, you may need to reload your workflow editor page to see the new version.

Feel free to reopen this issue, if the new version does not solve it.

**Closed as completed by godrei** 2017-02-01 13:19 UTC

**Comment by pakmee** [comment] 2017-02-01 14:29
@godrei Many thanks. Trying it now.

**Comment by pakmee** [comment] 2017-02-01 14:43
@godrei works minus some time outs am getting with the facebook sdk. I couldn't see 3.0.5 in the list. So I set it to use latest which solved my problem. Many thanks again for the super fast help. Been trying to shift the iOS Ci to bitrise.

**Comment by godrei** [comment] 2017-02-01 14:46
@pakmee great to hear that, let us know if you need any help!
