### ISSUE TITLE
please update carthage to 0.37.0 

### ISSUE THREAD

**Issue by kcome** [bitrise-steplib/steps-carthage#64] opened 2021-02-03 22:05 UTC
carthage 0.37.0 has been release. It supports xcframeworks so working with Apple Silicon is possible in carthage.

Could you kindly consider upgrading carthage in bitrise.io? Thanks.

**Comment by csk4ta** [comment] 2021-02-04 19:36
Hi @kcome! I checked with the team and they are working on upgrading Carthage everywhere ASAP. I don't have an estimate just yet but I’ll update this thread as soon as I have more info regarding the update. 😊 

Thanks,
Kata

**Comment by ykws** [comment] 2021-02-08 14:32
Bitrise Feature Request - Update Carthage 0.37.0
https://discuss.bitrise.io/t/update-carthage-to-0-37-0/15648

**Comment by csk4ta** [comment] 2021-03-04 21:28
Hello everyone, 

Thank you so much for your patience!

Our Infra team just confirmed that our brew repo version was updated earlier this week, so now it’s quick and easy to update Carthage during builds. Carthage still seems to be v0.36.0 on the stacks, but you can install 0.37.0 by adding this script to your workflow:

`brew upgrade carthage`

I hope this helps and thanks again for your patience!

**Comment by mateherber** [comment] 2021-03-11 16:54
Hi,

Carthage 0.37.0 had been released on our Xcode 12 stacks pre-installed and can be installed to the previous 11 and 10 stacks. Later they will also contain the latest version. I'm closing this issue now. Should you need further assistance please open a new issue or find our lovely support team on some of our channels.

**Closed as completed by mateherber** 2021-03-11 16:54 UTC
